### ISSUE TITLE
[Refactor]: User Views File

### ISSUE THREAD

**Issue by ShivamSinghal1** [Code-dig-ger/Backend#10]
In the `codedigger/user/views.py` - 

Many times we used hardcoded BAD REQUEST response, instead, we should use exceptions for that - 

Example - 
```python
return Response({'status': 'Failed','error' :'Email has not been provided'}, status=status.HTTP_400_BAD_REQUEST)
```
a better way to do this 
```python 
raise ValidationException('Email has not been provided')
```

Both are one-liners, but later one has some meaning and is nice looking. 

**There are almost 38 lines in this view which has to be updated like this.**

**Comment by MrNaif2018** [comment]
Hello, I would like to take it up. Does it need to be exceptions specifically, or it can be just a wrapper function returning Response with some pre-defined fields (status code) set? If response, should this be handled by middleware or exception handler?

EDIT: nevermind, it's the already created `ValidationException` from `codedigger/user/exception.py`
