### ISSUE TITLE
Optimize Github workflow autoyapf

### ISSUE THREAD

**Issue by ShivamSinghal1** [Code-dig-ger/Backend#21]
## Introduction
autoyapf is a [GitHub workflow](https://docs.github.com/en/actions/learn-github-actions) used to automatically reformatting the python code to PEP8 format using [yapf](https://github.com/google/yapf) whenever a pull request to master is initiated. 

## Current Behaviour 
Currently, it checks and reformats all the '.py' files in the repository but this can be optimize by just checking which file has been updated and only reformat those files. 

## Expected Behaviour
Optimize [autoyapf.yml](https://github.com/Code-dig-ger/Backend/blob/master/.github/workflows/autoyapf.yml) file so that it only reformat those files in PR which is updated by the contributor in the following PR.

**Comment by prahasR** [comment]
Hi @ShivamSinghal1 can you please assign this to me.

**Comment by ShivamSinghal1** [comment]
Yes, you can work on this.

**Comment by prahasR** [comment]
@ShivamSinghal1  created PR, please review.
