### ISSUE TITLE
Enhancement: Rating Change Reminder Email HTML CSS 

### ISSUE THREAD

**Issue by ShivamSinghal1** [Code-dig-ger/Backend#29]
Codedigger sends an email whenever participants participate in a Codeforces contest and rating changes.

It would be good if we can pretty the email using CSS or some animations. More ideas are welcomed. 

Current Email Format - 
![image](https://user-images.githubusercontent.com/44235074/135705212-d1669b8b-3481-4ef5-af4a-a7968dab7467.png)

Sample Context Data (to be feed to HTML)-
[See Doc see how to use templates in Django.](https://docs.djangoproject.com/en/3.2/topics/templates/)

```python
{
    "rating_change": {
        "contestId": 1540,
        "contestName": "Codeforces Round #728 (Div. 1)",
        "handle": "shivamsinghal1012",
        "rank": 20,
        "ratingUpdateTimeSeconds": 1624643400,
        "oldRating": 1800,
        "newRating": 2000,
        "oldRank": "expert",
        "newRank": "candidate master",
        "oldcolor": "user-blue",
        "newcolor": "user-violet",
        "isoldlegendary": False,
        "isnewlegendary": False,
    },
    "cdata": {
        "contest": {
            "name": "Codeforces Round #728 (Div. 1)",
            "contestId": 1540,
            "duration": 8100,
            "startTime": 1624635300,
            "Type": "R",
            "participants": 1500,
        },
        "worldRank": 20,
        "countryRank": 2,
        "organizationRank": 1,
        "totalCountryParticipants": 100,
        "totalOrganizationParticipants": 20,
    },
}
```
You can assume, you will get the data, but only need to update `codedigger/templates/codeforces/rating_reminder.html`.

Requied - HTML, CSS knowledge.

### To run your code at local - 

Pull `feat/codeforces/rating_reminder` branch. 

Run server as mentioned in the README.md file.

Visit [http://127.0.0.1:8000/codeforces/rating-change-email](http://127.0.0.1:8000/codeforces/rating-change-email)

The `codedigger/templates/codeforces/rating_reminder.html` template is rendered from the `codedigger/codeforces/views.py` file  `rating_change_email` function.

EMAIL Best Practice
1. Make sure your HTML email is responsive for different screen sizes and devices.
2. Make sure your styling works for different email clients.
3. Be conscious of how long your HTML emails take to load.

**Comment by mihir1739** [comment]
Please assign this issue to me..

**Comment by ShivamSinghal1** [comment]
Okay

**Comment by ShivamSinghal1** [comment]
Hi @mihir1739, are you working on this issue?

**Comment by vishnu-sagubandi** [comment]
Hey, I would like to work on this.

**Comment by ShivamSinghal1** [comment]
Pull `feat/codeforces/rating_reminder` and work on this branch. Feel free to ask any type of doubt/ help.

**Comment by vishnu-sagubandi** [comment]
> Pull `feat/codeforces/rating_reminder` and work on this branch. Feel free to ask any type of doubt/ help.

Yeah sure and thank You.

**Comment by vishnu-sagubandi** [comment]
Hey !! Please have look at the following screenshots from windows and Iphone 8. If you can finalize, I will create a PR.
<br>
Windows -
<img src="https://user-images.githubusercontent.com/64656396/136669493-b83dc937-e093-4822-ad9b-d6c9256d9439.png" width="75%"/>
<br>
Iphone -
<img src="https://user-images.githubusercontent.com/64656396/136669309-64a721ef-4b3e-4e02-9fcc-cae90615a581.png" width="250px"/>

**Comment by vishnu-sagubandi** [comment]
Sorry for the typo. It is candid master(not expert master)😅

**Comment by ShivamSinghal1** [comment]
Hi @vishnu-sagubandi, 

The UI looks pretty amazing. But can we do something if someone's rating decreases? Something like a motivational theme. 

Also, Standings would contain a number of participants too.

**Comment by ShivamSinghal1** [comment]
Optional, can we develop a button to share this to social media/ LinkedIn.

**Comment by vishnu-sagubandi** [comment]
> Hi @vishnu-sagubandi,
> 
> The UI looks pretty amazing. But can we do something if someone's rating decreases? Something like a motivational theme.
> 
> Also, Standings would contain a number of participants too.

Will try that and update you soon.

**Comment by vishnu-sagubandi** [comment]
Have a look at this @ShivamSinghal1
<br>
Increases
<img src="https://user-images.githubusercontent.com/64656396/136669493-b83dc937-e093-4822-ad9b-d6c9256d9439.png" width="75%"/><br>
Decreases
<img width="75%" src="https://user-images.githubusercontent.com/64656396/136686994-418e392b-274d-4344-9c80-4c494a05db46.png">

**Comment by ShivamSinghal1** [comment]
Both are Nice! 

Amazing work!! Create a PR. If you face any issue. Please let me know.

**Comment by vishnu-sagubandi** [comment]
Hii @ShivamSinghal1 ,
Sorry for the delay. I went on a trip unexpectedly.
Can you plz explain how the function `islegendary()` works??

**Comment by ShivamSinghal1** [comment]
No issue @vishnu-sagubandi

Basically, `islegendary` function return true, if user rating is above 3000. That means the User is Legendary grandmaster and the color for that user, first letter black.
