### ISSUE TITLE
feat: Add a route to Search Codeforces User from the database.

### ISSUE THREAD

**Issue by ShivamSinghal1** [Code-dig-ger/Backend#30]
Would like to add a route where we can get all the list of users matching the given query. 

Example route - 

`/codeforces/search?q=tou`

GET request to this route would provide me a list of matching Codeforces users (atmost 5 most similar)

Example response - 

```json
{
    "status": "OK",
    "result": [
        {
            "name": "Gennady",
            "handle": "tourist",
            "profile" : "https://userpic.codeforces.org/422/title/50a270ed4a722867.jpg"
        },
        {
            "name": "Tourist",
            "handle": "touristt",
            "profile" : "https://userpic.codeforces.org/no-title.jpg"
        }
    ]
}
```

Search users from our database, not by using API. 
We are storing all the codeforces users in our database only `codedigger.codeforces.models.user`.
Query to the database to get matching users.

Add a test case to test your route.

**Comment by kmarrip** [comment]
hey @ShivamSinghal1 
would love to work on this , i personally used codedigger for a while . would like to give back

**Comment by ShivamSinghal1** [comment]
Glad you're interested to work. Go ahead.

**Comment by kmarrip** [comment]
hey @ShivamSinghal1  you haven't assigned the issue to me yet. can you do that so i can start working on feature 
and btw do you guys have any discord server where we can talk??

**Comment by ShivamSinghal1** [comment]
Assigned you the issue. Yes, we have a Discord server as well. [JOIN](https://discord.gg/4ZeNgUn7cF)

**Comment by kmarrip** [comment]
@ShivamSinghal1 i wont be able to work on this sorry

**Comment by ShivamSinghal1** [comment]
Its okay @chaithanyaMarripati.
